### ISSUE TITLE
Milestone 1

### ISSUE THREAD

**Issue by meneal** [RobotWithFeelings/CSC710_Project#2]
What should we put into M1, and what should our deadline be?

**Comment by acmarrs** [comment]
Looks like Milestone 1 is:

Paper Outline
Paper Related Work
Basic Functioning Website for study

with a deadline of Monday, March 21st.

**Comment by meneal** [comment]
Since we've already covered the Website and I've added the paper stuff to m1 I'll just close this issue.  If we end up needing stuff for the paper outline we can make that into an issue too.
